@host = http://localhost:8080
@userPassUser = Alevander
@userPassPassword = secret123

### 1) Registrera med användarnamn & lösenord
POST {{host}}/auth/register
Content-Type: application/json

{
  "username": "{{userPassUser}}",
  "password": "{{userPassPassword}}"
}

### 2) Logga in med användarnamn & lösenord
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "{{userPassUser}}",
  "password": "{{userPassPassword}}"
}

> {% client.global.set("token", response.body.token) %}

### 3) Hämta activityLog
GET {{host}}/activityLog
Authorization: Bearer {{token}}
Content-Type: application/json

### 4) Hämta profilinfo
GET {{host}}/user/profile
Authorization: Bearer {{token}}
Content-Type: application/json

### 5) Ändra profilinfo
PUT {{host}}/user/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Alevander",
  "lastName": "Grenander",
  "email": "bob@gmail.com",
  "phoneNumber": "+4670-1234567",
  "preferredLanguage": "sv",
  "emailNotifications": false,
  "smsNotifications": false,
  "timeZone": "UTC+1"
}

### 6) Ändra profilinfo (ett fält)
PUT {{host}}/user/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Alexander"
}